gem"rake", Gem::Version.new(RUBY_VERSION) < Gem::Version.new("1.9.3") ? "~>10.3" : ">= 10.3"
gem "simplecov"
gem "simplecov-rcov"
gem "rubocop", :require => false
group :test do
  gem "rspec", ">= 3.2"
  # Older versions of some gems required for Ruby 1.8.7 support
  platforms :ruby_18 do
    gem "activesupport", "~> 3.2.21"
    gem "i18n", "~> 0.6.11"
  end
  platforms :ruby_18, :ruby_19 do
    gem "mime-types", "~> 1.25"
    gem "addressable", "~> 2.3.0"
  end
  platforms :ruby_18, :ruby_19, :ruby_20, :ruby_21 do
    gem "rack", "~> 1.6"
  end
  platforms :jruby, :ruby_19, :ruby_20, :ruby_21, :ruby_22 do
    gem "aruba", "~> 0.7.4"
    gem "capybara"
    gem "nokogiri", RUBY_VERSION < "2.1" ? "~> 1.6.0" : ">= 1.7"
    gem "cucumber"
    gem "phantomjs", "~> 2.1"
    gem "poltergeist"
    # gem "rubocop", "0.48.1" unless RUBY_VERSION.start_with?("1.")
    gem "test-unit"
  end
  gem "json", RUBY_VERSION.start_with?("1.") ? "~> 1.8" : "~> 2.0"
end
