
require "rubygems"
require "bundler/setup"

require "rubocop/rake_task"
RuboCop::RakeTask.new(:rubocop) do |rubocop|
   rubocop.fail_on_error = false
   rubocop.patterns = FileList['/root/RORCIaditi/simplecov/spec/*.rb']

  rubocop.options = ["--out", "rubocop-report.html"]
end

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(:spec) do |spec|
   spec.pattern = FileList["spec/*_spec.rb"]
   spec.rspec_opts = "--format html --out reports/rspec_results.html"

  require "simplecov"
  SimpleCov.start

  SimpleCov.coverage_dir("tmp/coverage")
end
