#!/usr/bin/env rake

require "rubygems"
require "bundler/setup"
# require "spec_helper"

Bundler::GemHelper.install_tasks

# See https://github.com/colszowka/simplecov/issues/171
# desc "Set permissions on all files so they are compatible with both user-local and system-wide installs"
# task :fix_permissions do
#  system 'bash -c "find . -type f -exec chmod 644 {} \; && find . -type d -exec chmod 755 {} \;"'
# end
# E Enforce proper permissions on each build
Rake::Task[:build]

require "rspec/core/rake_task"
# require "simplecov"
# require "simplecov-rcov"
RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = FileList["spec/*_spec.rb"]
  spec.rspec_opts = "--format html --out reports/rspec_results.html"

  require "simplecov"

  SimpleCov.coverage_dir("tmp/coverage")

  SimpleCov.start

  # spec.simplecov.coverage_dir("tmp/coverage")
  # spec.simplecov.start
end

namespace :rspec_report do
  desc "Run all specs and generate RSpec report in HTML"
  task :html => :spec

  desc "Run all specs, generate RSpec report and open it in the browser"
  task :browser do
    Rake::Task[:spec].invoke
    `open reports/rspec_results.html` # This only works if running OS X.
  end
end
require "rubocop/rake_task"

desc "Execute rubocop -DR"
RuboCop::RakeTask.new(:rubocop) do |tsk|
  tsk.options = ["-DR"] # Rails, display cop name
  tsk.fail_on_error = false
  tsk.patterns = FileList['/root/RORCIaditi/simplecov/spec/*.rb']
 # tsk.formatters = ["html"]
  tsk.options = ["--out", "rubocop-report.html"]
#  tsk.RUBOCOP_OPTS = "--format html -o rubocop.html"
#   tsk.formatters = "--format html -o rubocop.html"
#   tsk.formatters = ["html"]
end

# task :rubocop do
# Your code goes here
# sh 'rubocop'

# end

 task :default => [:spec]

# begin

# require "rubocop"
# ask test: rubocop

# ask :rubocop do
# sh 'rubocop'
# nd
# RuboCop::RakeTask.new
# rescue LoadError
# task :rubocop do
#  $stderr.puts "Rubocop is disabled"
# end
# end

# Cucumber integration test suite is for impls that work with simplecov only - a.k.a. 1.9+
# if RUBY_VERSION.start_with? "1.8"

# else
# require "cucumber/rake/task"
# Cucumber::Rake::Task.new

# if RUBY_VERSION.start_with? "1.9"
#  task :default => [:spec, :cucumber]
# else
# task :default => [:rubocop, :spec, :cucumber]
# end
# end
